### ISSUE TITLE
Full Code 

### ISSUE THREAD

**Issue by samatzp** [HKARLI/sweet_grocery#1]
Hi Bro How i can get full source code ?

**Comment by hasankarli** [comment]
The attached files do NOT work as a standalone project. Instead, you should use them to compare my code (in the lib/ folder, as well as the pubspec.yaml file) to your code. Experience shows, that this helps you spot + fix 99% of all errors you might encounter. If you want to run the code, you can do that as well though. 
Follow these steps
1) Create a new Flutter project via flutter create some_project
2) Replace the lib/ folder and the pubspec.yaml file with the attached files
3) Possibly add assets like images or fonts or adjust the AndroidManifest.xml / Info.plist file to add data/ permissions (only if covered in the previous lectures)
4) Firebase add auth open email and change rules {
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null",
  	"products": {
    	".indexOn": ["userId"]
  	}
  }
} 
5)  flutter packages get
6 ) flutter run
